"""Add email verification

Revision ID: b4315b3e7a70
Revises: 8e61d49628fb
Create Date: 2026-07-05 17:49:04.839116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4315b3e7a70'
down_revision = '8e61d49628fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
                                'is_verified',
                                sa.Boolean(),
                                nullable=False,
                                server_default=sa.false()
                            ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
