"""add password hash to user

Revision ID: b9c9520492f5
Revises: initial_schema
Create Date: 2026-06-01 18:27:36.782773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c9520492f5'
down_revision = 'initial_schema'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table(
        'users',
        schema=None
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                'password_hash',
                sa.String(length=255),
                nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
